#include "main.h"
#include "functions.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/title.h"
#include "images/win.h"
#include "images/lose.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state
{
  START,
  START_WAIT,
  SET_UP_PLAY,
  PLAY,
  WIN,
  LOSE,
};

int main(void)
{
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;
  gameState currentState;

  while (1)
  {
    currentButtons = BUTTONS; // Load the current state of the buttons
    //drawRectDMA(30, 40, 5, 5, RED);
    //drawImageDMA(50, 50, 50, 50, backgrounded);
    //fillScreenDMA(RED);
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state)
    {

    case START:
      waitForVBlank();
      drawFullScreenImageDMA(title);
      state = START_WAIT;
      break;

    case START_WAIT:
      if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons))
      {
        state = SET_UP_PLAY;
      }
      break;
      ;

    case SET_UP_PLAY:
      waitForVBlank();
      currentState = setUpGame(currentState);
      state = PLAY;
      break;

    case PLAY:
      waitForVBlank();
      currentState = process(currentState, currentButtons, previousButtons);

      //waitForVBlank();
      currentState = update(&currentState);
      if (currentState.win > 0) {
        state = WIN;
      } else if (currentState.win < 0) {
        state = LOSE;
      }
      break;

    case WIN:
      waitForVBlank();
      drawFullScreenImageDMA(win);
      break;
    case LOSE:
      waitForVBlank();
      drawFullScreenImageDMA(lose);
      // state = ?
      break;
    }
    if (KEY_DOWN(BUTTON_SELECT, currentButtons))
    {
      fillScreenDMA(WHITE);
      state = START;
    }
    previousButtons = currentButtons; // Store the current state of the buttons
  }

  // UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
